name: Metrics Lines
on:
  # Schedule daily updates
  schedule: 
    - cron: "0 0 * * 1"
  workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.lines.history.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_lines: yes
            plugin_lines_sections: repositories